spring.application.name=ProjetData
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dataFoot
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API Sports
apisports.baseUrl=https://v3.football.api-sports.io
apisports.key=${APISPORTS_KEY}
jwt.secret=${JWT_SECRET}
